package com.aurelioklv.enigma.component

enum class RotorType(val wiringString: String, val notches: List<Char>) {
    ROTOR_I("EKMFLGDQVZNTOWYHXUSPAIBRCJ", listOf('Q')),
    ROTOR_II("AJDKSIRUXBLHWTMCQGZNPYFVOE", listOf('E')),
    ROTOR_III("BDFHJLCPRTXVZNYEIWGAKMUSQO", listOf('V')),
    ROTOR_IV("ESOVPZJAYQUIRHXLNFTGKDCMWB", listOf('J')),
    ROTOR_V("VZBRGITYUPSDNHLXAWMJQOFECK", listOf('Z')),
    ROTOR_VI("JPGVOUMFYQBENHZRDKASXLICTW", listOf('M', 'Z')),
    ROTOR_VII("NZJHGRCXMYSWBOUFAIVLPEKQDT", listOf('M', 'Z')),
    ROTOR_VIII("FKQHTLXOCBJSPDZRAMEWNIUYGV", listOf('M', 'Z')),
    ROTOR_I_SONDER("VEOSIRZUJDQCKGWYPNXAFLTHMB", listOf('Q')),
    ROTOR_II_SONDER("UEMOATQLSHPKCYFWJZBGVXIDNR", listOf('E')),
    ROTOR_III_SONDER("TZHXMBSIPNURJFDKEQVCWGLAOY", listOf('V')),
    ROTOR_BETA("LEYJVCNIXWPBQMDRTAKZGFUHOS", listOf('Z')),
    ROTOR_GAMMA("FSOKANUERHMBTIYCWLQPZXVGJD", listOf('Z')),

    //    Norenigma
    ROTOR_I_NORENIGMA("WTOKASUYVRBXJHQCPZEFMDINLG", listOf('Q')),
    ROTOR_II_NORENIGMA("GJLPUBSWEMCTQVHXAOFZDRKYNI", listOf('E')),
    ROTOR_III_NORENIGMA("JWFMHNBPUSDYTIXVZGRQLAOEKC", listOf('V')),
    ROTOR_IV_NORENIGMA("FGZJMVXEPBWSHQTLIUDYKCNRAO", listOf('J')),
    ROTOR_V_NORENIGMA("HEJXQOTZBVFDASCILWPGYNMURK", listOf('Z')),
}

enum class ReflectorType(val wiringString: String) {
    REFLECTOR_UKW_B_ENIGMA_M3("YRUHQSLDPXNGOKMIEBFZCWVJAT"),
    REFLECTOR_UKW_C_ENIGMA_M3("FVPJIAOYEDRZXWGCTKUQSBNMHL"),
    REFLECTOR_UKW_A_ENIGMA_I("EJMZALYXVBWFCRQUONTSPIKHGD"),
    REFLECTOR_UKW_B_ENIGMA_I("YRUHQSLDPXNGOKMIEBFZCWVJAT"),
    REFLECTOR_UKW_C_ENIGMA_I("FVPJIAOYEDRZXWGCTKUQSBNMHL"),
    REFLECTOR_UKW_B_THIN("ENKQAUYWJICOPBLMDXZVFTHRGS"),
    REFLECTOR_UKW_C_THIN("RDOBJNTKVEHMLFCWZAXGYIPSUQ"),
    REFLECTOR_UKW_SONDER("CIAGSNDRBYTPZFULVHEKOQXWJM"),
    REFLECTOR_UKW_NORENIGMA("MOWJYPUXNDSRAIBFVLKZGQCHET")
}